global:
  ethereum:
    network: zhejiang
  networkConfigs:
    zhejiang:
      execution:
        config:
          bootnodes: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/bootnodes.txt
          genesis_geth: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/genesis.json
          nethermind_genesis_json: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/chainspec.json
          besu_genesis_json: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/besu.json
        args:
          geth:
            - --bootnodes="$(tr '\n' ',' < /data/execution/bootnode.txt)" \
            - --networkid=$(cat /data/execution/chainid.txt)
          nethermind:
            - --Init.ChainSpecPath="/data/execution/nethermind_genesis.json"
          besu:
            - --network-id=$(cat /data/execution/chainid.txt) \
            - --genesis-file="/data/execution/besu_genesis.json" \
            - --bootnodes="$(tr '\n' ',' < /data/execution/bootnode.txt)"
          erigon:
            - --bootnodes="$(tr '\n' ',' < /data/execution/bootnode.txt)" \
            - --networkid=$(cat /data/execution/chainid.txt)
      consensus:
        config:
          bootnodes: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/bootstrap_nodes.txt
          config_yaml: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/config.yaml
          genesis_ssz: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/genesis.ssz
          deploy_block_txt: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/deploy_block.txt
          deposit_contract_txt: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/deposit_contract.txt
          deposit_contract_block_txt: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/deposit_contract_block.txt
          deposit_contract_block_hash_txt: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/deposit_contract_block_hash.txt
        args:
          lighthouse:
            - --testnet-dir=/data/consensus/testnet_spec \
            - --boot-nodes="$(tr '\n' ',' < /data/consensus/testnet_spec/bootstrap_nodes.txt)"
          prysm:
            - --bootstrap-node="$(head -n 1 /data/consensus/testnet_spec/bootstrap_nodes.txt)" \
            - --genesis-state /data/consensus/testnet_spec/genesis.ssz \
            - --chain-config-file=/data/consensus/testnet_spec/config.yaml
          teku:
            - --p2p-discovery-bootnodes="$(tr '\n' ',' < /data/consensus/testnet_spec/bootstrap_nodes.txt)" \
            - --network=/data/consensus/testnet_spec/config.yaml \
            - --initial-state=/data/consensus/testnet_spec/genesis.ssz
          nimbus:
            - --network="/data/consensus/testnet_spec" \
            - --bootstrap-node="$(tr '\n' ',' < /data/consensus/testnet_spec/bootstrap_nodes.txt)"
          lodestar:
            - --network.connectToDiscv5Bootnodes
            - --testnet-dir=/data/consensus/testnet_spec \
            - --boot-nodes="$(tr '\n' ',' < /data/consensus/testnet_spec/bootstrap_nodes.txt)"
geth:
  image:
    tag: v0.11.2
    pullPolicy: IfNotPresent

nethermind:
  image:
    repository: nethermindeth/nethermind
    tag: "1.17.0"
    pullPolicy: IfNotPresent

besu:
  image:
    repository: hyperledger/besu
    tag: 23.1.1-RC1
    pullPolicy: IfNotPresent


lighthouse:
  image:
    repository: sigp/lighthouse
    tag: v3.5.0
    pullPolicy: IfNotPresent

prysm:
  image:
    repository: ethpandaops/prysm # Official prysm image doesnt have `sh` which is required for p2pnodeport
    tag: v3.2.1
    pullPolicy: IfNotPresent

teku:
  image:
    repository: consensys/teku
    tag: 23.2.0
    pullPolicy: IfNotPresent

nimbus:
  image:
    repository: statusim/nimbus-eth2
    tag: amd64-v23.2.0
    pullPolicy: IfNotPresent

lodestar:
  image:
    repository: chainsafe/lodestar
    tag: v1.5.0-rc0
    pullPolicy: IfNotPresent

erigon:
  image:
    repository: thorax/erigon
    tag: v2.39.0
    pullPolicy: IfNotPresent