global:
  ethereum:
    network: zhejiang
  networkConfigs:
    zhejiang:
      execution:
        config:
          bootnodes: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/bootnodes.txt
          genesis_geth: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/genesis.json
          nethermind_genesis_json: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/chainspec.json
          besu_genesis_json: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/besu.json
        args:
          geth:
            - --bootnodes="$(tr '\n' ',' < /data/execution/bootnode.txt)" \
            - --networkid=$(cat /data/execution/chainid.txt)
          nethermind:
            - --Init.ChainSpecPath="/data/execution/nethermind_genesis.json"
          besu:
            - --network-id=$(cat /data/execution/chainid.txt) \
            - --genesis-file="/data/execution/besu_genesis.json" \
            - --bootnodes="$(tr '\n' ',' < /data/execution/bootnode.txt)"
          erigon:
            - --bootnodes="$(tr '\n' ',' < /data/execution/bootnode.txt)" \
            - --networkid=$(cat /data/execution/chainid.txt)
      consensus:
        config:
          bootnodes: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/bootstrap_nodes.txt
          config_yaml: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/config.yaml
          genesis_ssz: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/genesis.ssz
          deploy_block_txt: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/deploy_block.txt
          deposit_contract_txt: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/deposit_contract.txt
          deposit_contract_block_txt: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/deposit_contract_block.txt
          deposit_contract_block_hash_txt: https://raw.githubusercontent.com/ethpandaops/withdrawals-testnet/master/zhejiang-testnet/custom_config_data/deposit_contract_block_hash.txt
        args:
          lighthouse:
            - --testnet-dir=/data/consensus/testnet_spec \
            - --boot-nodes="$(tr '\n' ',' < /data/consensus/testnet_spec/bootstrap_nodes.txt)"
          prysm:
            - --bootstrap-node="$(head -n 1 /data/consensus/testnet_spec/bootstrap_nodes.txt)" \
            - --genesis-state /data/consensus/testnet_spec/genesis.ssz \
            - --chain-config-file=/data/consensus/testnet_spec/config.yaml
          teku:
            - --p2p-discovery-bootnodes="$(tr '\n' ',' < /data/consensus/testnet_spec/bootstrap_nodes.txt)" \
            - --network=/data/consensus/testnet_spec/config.yaml \
            - --initial-state=/data/consensus/testnet_spec/genesis.ssz
          nimbus:
            - --network="/data/consensus/testnet_spec" \
            - --bootstrap-node="$(tr '\n' ',' < /data/consensus/testnet_spec/bootstrap_nodes.txt)"
          lodestar:
            - --network.connectToDiscv5Bootnodes=true \
            - --paramsFile=/data/consensus/testnet_spec/config.yaml \
            - --genesisStateFile=/data/consensus/testnet_spec/genesis.ssz \
            - --bootnodes="$(tr '\n' ',' < /data/consensus/testnet_spec/bootstrap_nodes.txt)"
