image:
  repository: ethereum/client-go
  tag: latest
  pullPolicy: Always

initContainers:
  initGenesis:
    image: 
      repository: alpine
      tag: latest
      pullPolicy: IfNotPresent

    enabled: true

extraArgs: []

extraContainerPorts: []

extraEnv: []

customCommand: []

resources:
  {}
  # requests:
  #   cpu: 2000m
  #   memory: 4000Mi


# -- Readiness probe
# @default -- See `values.yaml`
livenessProbe:
  tcpSocket:
    port: exe-http-rpc
  initialDelaySeconds: 180
  periodSeconds: 60
  failureThreshold: 5

# -- Readiness probe
# @default -- See `values.yaml`
readinessProbe:
  tcpSocket:
    port: exe-http-rpc
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3