{{- define "ethereum-sync-tests.initContainers" }}
{{ include "common.initContainers" .Subcharts.common }}
{{- if eq .Values.global.ethereum.execution.client.name "geth" }}
{{ include "geth.initContainers" .Subcharts.geth }}
{{- end }}
{{- if eq .Values.global.ethereum.execution.client.name "nethermind" }}
{{ include "nethermind.initContainers" .Subcharts.nethermind }}
{{- end }}
{{- if eq .Values.global.ethereum.execution.client.name "besu" }}
{{ include "besu.initContainers" .Subcharts.besu }}
{{- end }}
{{- if eq .Values.global.ethereum.execution.client.name "erigon" }}
{{ include "erigon.initContainers" .Subcharts.erigon }}
{{- end }}
{{- if eq .Values.global.ethereum.consensus.client.name "lighthouse" }}
{{ include "lighthouse.initContainers" .Subcharts.lighthouse }}
{{- end }}
{{- if eq .Values.global.ethereum.consensus.client.name "prysm" }}
{{ include "prysm.initContainers" .Subcharts.prysm }}
{{- end }}
{{- if eq .Values.global.ethereum.consensus.client.name "teku" }}
{{ include "teku.initContainers" .Subcharts.teku }}
{{- end }}
{{- if eq .Values.global.ethereum.consensus.client.name "nimbus" }}
{{ include "nimbus.initContainers" .Subcharts.nimbus }}
{{- end }}
{{- if eq .Values.global.ethereum.consensus.client.name "lodestar" }}
{{ include "lodestar.initContainers" .Subcharts.lodestar }}
{{- end }}
{{- end }}