apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ethereum-sync-tests.fullname" . }}-checks
  labels:
    {{- include "ethereum-sync-tests.labels" . | nindent 4 }}
data:
  "execution.sh": |-
{{- include "ethereum-sync-tests.status-checking-execution" . | nindent 8 }}
  "consensus.sh": |-
{{- include "ethereum-sync-tests.status-checking-consensus" . | nindent 8 }}
