apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ethereum-sync-tests.fullname" . }}
  labels:
    {{- include "ethereum-sync-tests.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.cronjob.annotations }}
    {{- toYaml .Values.cronjob.annotations | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  suspend: {{ .Values.cronjob.suspend }}
  {{- if .Values.cronjob.concurrencyPolicy }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  {{- end }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  {{- if .Values.cronjob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  {{- end }}
  jobTemplate: 
    spec:
     {{- include "ethereum-sync-tests.job-spec" . | nindent 6 }}
