{{- define "ethereum-sync-tests.initContainers" }}
{{ include "common.initContainers" .Subcharts.common }}
{{- if eq .Values.global.ethereum.execution.client.name "geth" }}
{{ include "geth.initContainers" .Subcharts.geth }}
{{- end }}
{{- end }}