{{- define "ethereum-sync-tests.volumes" }}
{{- if .Values.global.p2pNodePort.enabled }}
- name: env-nodeport
  emptyDir: {}
{{- end }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | nindent 8}}
{{- end }}
- name: config
  emptyDir: {}
  # configMap:
    # name: {{ include "ethereum-sync-tests.fullname" . }}

{{- if .Values.persistence.enabled }}
- name: storage
  persistentVolumeClaim:
    claimName: {{ include "ethereum-sync-tests.fullname" . }}
{{- end }}
{{- if not .Values.persistence.enabled }}
- name: storage
  emptyDir: {}
{{- else if .Values.persistence.existingClaim }}
- name: storage
  persistentVolumeClaim:
    claimName: {{ .Values.persistence.existingClaim }}
{{- end }}
{{- end }}