image:
  repository: statusim/nimbus-eth2
  tag: amd64-latest
  pullPolicy: Always

initContainers:
  initGenesis:
    image: 
      repository: alpine
      tag: latest
      pullPolicy: IfNotPresent

    enabled: true

defaultBinaryPath: /home/user/nimbus-eth2/build/nimbus_beacon_node

extraArgs: []

extraContainerPorts: []

extraEnv: []

customCommand: []

resources:
  {}
  # requests:
  #   cpu: 2000m
  #   memory: 4000Mi