image:
  repository: statusim/nimbus-eth2
  tag: amd64-latest
  pullPolicy: Always

initContainers:
  initGenesis:
    image: 
      repository: alpine
      tag: latest
      pullPolicy: IfNotPresent

    enabled: true

defaultBinaryPath: /home/user/nimbus-eth2/build/nimbus_beacon_node

extraArgs: []

extraContainerPorts: []

extraEnv: []

customCommand: []

resources:
  {}
  # requests:
  #   cpu: 2000m
  #   memory: 4000Mi


# -- Liveness probe
# @default -- See `values.yaml`
# livenessProbe:
#   tcpSocket:
#     port: con-http-api
#   initialDelaySeconds: 180
#   periodSeconds: 60
#   failureThreshold: 5

# -- Readiness probe
# @default -- See `values.yaml`
readinessProbe:
  tcpSocket:
    port: con-http-api
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
