---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-general
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  hostPath:
    path: /persistence/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-general
spec:
  volumeName: pv-general
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi