statusChecker:
  image:
    repository: alpine
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    {}
  # requests:
  #   cpu: 16m
  #   memory: 32Mi

metricsExporter:
  enabled: true
  image:
    repository: samcm/ethereum-metrics-exporter
    tag: main
    pullPolicy: Always

  resources:
    {}
  # requests:
  #   cpu: 16m
  #   memory: 32Mi