coordinator:
  enabled: true
  port: 9095
  image:
    repository: samcm/sync-test-coordinator
    tag: latest
    pullPolicy: IfNotPresent

metricsExporter:
  enabled: true
  image:
    repository: samcm/ethereum-metrics-exporter
    tag: 0.11.1
    pullPolicy: Always

  resources:
    {}
  # requests:
  #   cpu: 16m
  #   memory: 32Mi
  config_yaml:
    consensus:
      enabled: true
      url: "http://localhost:5052"
      name: "consensus-client"
    execution:
      enabled: true
      url: "http://localhost:8545"
      name: "execution-client"
      modules:
        - "eth"
        - "net"
        - "web3"
        - "txpool"
    diskUsage:
      enabled: true
      directories:
      - /data/execution
      - /data/consensus
