coordinator:
  enabled: true
  port: 9095
  image:
    repository: samcm/sync-test-coordinator
    tag: latest
    pullPolicy: IfNotPresent

metricsExporter:
  enabled: true
  image:
    repository: samcm/ethereum-metrics-exporter
    tag: main
    pullPolicy: Always

  resources:
    {}
  # requests:
  #   cpu: 16m
  #   memory: 32Mi