apiVersion: v2
name: ethereum-sync-tests
description: A Helm chart for testing how long it takes to sync Ethereum Consensus & Execution clients

type: application

# This is the chart version. This version number should be incremented each time you make changes to the chart.
version: 0.37.0

# This is the version number of the application being deployed. Doesn't really apply to us, we are deploying multiple
# downstream applications, each with their own versions.
appVersion: "0.0.0"

maintainers:
  - name: "samcm"
    email: "sam.calder-mason@ethereum.org"

dependencies:
- name: "common"
  version: "0.1.0"
  repository: "file://charts/common"
- name: "geth"
  version: "0.1.0"
  repository: "file://charts/geth"
- name: "lighthouse"
  version: "0.1.0"
  repository: "file://charts/lighthouse"
- name: "prysm"
  version: "0.1.0"
  repository: "file://charts/prysm"
- name: "nethermind"
  version: "0.1.0"
  repository: "file://charts/nethermind"
- name: "teku"
  version: "0.1.0"
  repository: "file://charts/teku"
- name: "besu"
  version: "0.1.0"
  repository: "file://charts/besu"