initContainers:
  initGenesis:
    enabled: true

    image: 
      repository: alpine
      tag: latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: false
      runAsUser: 0

extraArgs: []

extraContainerPorts: []

customCommand: []

resources:
  {}
  # requests:
  #   cpu: 2000m
  #   memory: 4000Mi