
   
name: Integration test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Install chart
        run: >
          helm install ethereum-sync-test ./charts/ethereum-sync-test \
            -f ./charts/ethereum-sync-test/values.yaml \
            -f ./charts/ethereum-sync-test/values/tests/starts-syncing.yaml \
            -f ./charts/ethereum-sync-test/values/networks/kiln.yaml \
            -f ./charts/ethereum-sync-test/values/clients/execution/geth.yaml \
            -f ./charts/ethereum-sync-test/values/clients/consensus/lighthouse.yaml
      - name: Run test
        run: >
          helm test ethereum-sync-test --timeout=10m