name: Integration test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.head_ref }}-${{ matrix.network }}-${{ matrix.consensus }}-${{ matrix.execution }}-${{ matrix.test }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        consensus: [teku, prysm, lighthouse, nimbus, lodestar]
        execution: [geth, nethermind, erigon]
        network: [ropsten, kiln]
        test: [starts-syncing, is-healthy]
        exclude:
        - execution: nethermind
          test: starts-syncing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Install chart
        run: >
          helm install ethereum-sync-test ./charts/ethereum-sync-test \
            -f ./charts/ethereum-sync-test/values.yaml \
            -f ./charts/ethereum-sync-test/values/tests/${{ matrix.test }}.yaml \
            -f ./charts/ethereum-sync-test/values/networks/${{ matrix.network }}.yaml \
            -f ./charts/ethereum-sync-test/values/clients/execution/${{ matrix.execution }}.yaml \
            -f ./charts/ethereum-sync-test/values/clients/consensus/${{ matrix.consensus }}.yaml \
            --set common.coordinator.lameduckSeconds=1 \

      - name: Run test
        run: >
          helm test ethereum-sync-test --timeout=5m

      - name: Coordinator Pod Logs
        if: always()
        run: >
          kubectl logs pod/$(kubectl get pods -o name | grep ethereum-sync-test | cut -d/ -f2) -c coordinator --tail 250
      - name: Execution Pod Logs
        if: always()
        run: >
          kubectl logs pod/$(kubectl get pods -o name | grep ethereum-sync-test | cut -d/ -f2) -c ${{ matrix.execution }} --tail 250
      - name: Consensus Pod Logs
        if: always()
        run: >
          kubectl logs pod/$(kubectl get pods -o name | grep ethereum-sync-test | cut -d/ -f2) -c ${{ matrix.consensus }}-beacon --tail 250
