name: Integration test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  is-healthy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        consensus: [teku, prysm, lighthouse, nimbus]
        execution: [geth, besu, nethermind]
        network: [ropsten, kiln]
        exclude:
        - network: kiln
          consensus: nimbus
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      # - name: Template chart
      #   run: >
      #     helm template ethereum-sync-test ./charts/ethereum-sync-test \
      #       -f ./charts/ethereum-sync-test/values.yaml \
      #       -f ./charts/ethereum-sync-test/values/tests/is-healthy.yaml \
      #       -f ./charts/ethereum-sync-test/values/networks/${{ matrix.network }}.yaml \
      #       -f ./charts/ethereum-sync-test/values/clients/execution/${{ matrix.execution }}.yaml \
      #       -f ./charts/ethereum-sync-test/values/clients/consensus/${{ matrix.consensus }}.yaml

      - name: Install chart
        run: >
          helm install ethereum-sync-test ./charts/ethereum-sync-test \
            -f ./charts/ethereum-sync-test/values.yaml \
            -f ./charts/ethereum-sync-test/values/tests/is-healthy.yaml \
            -f ./charts/ethereum-sync-test/values/networks/${{ matrix.network }}.yaml \
            -f ./charts/ethereum-sync-test/values/clients/execution/${{ matrix.execution }}.yaml \
            -f ./charts/ethereum-sync-test/values/clients/consensus/${{ matrix.consensus }}.yaml

      - name: Run test
        run: >
          helm test ethereum-sync-test --timeout=5m

      - name: Coordinator Pod Logs
        if: always()
        run: >
          kubectl logs pod/$(kubectl get pods -o name | grep ethereum-sync-test | cut -d/ -f2) -c coordinator --tail 250
      - name: Execution Pod Logs
        if: always()
        run: >
          kubectl logs pod/$(kubectl get pods -o name | grep ethereum-sync-test | cut -d/ -f2) -c ${{ matrix.execution }} --tail 250
      - name: Consensus Pod Logs
        if: always()
        run: >
          kubectl logs pod/$(kubectl get pods -o name | grep ethereum-sync-test | cut -d/ -f2) -c ${{ matrix.consensus }}-beacon --tail 250

  starts-syncing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        consensus: [teku, prysm, lighthouse]
        execution: [geth]
        network: [ropsten] 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      # - name: Template chart
      #   run: >
      #     helm template ethereum-sync-test ./charts/ethereum-sync-test \
      #       -f ./charts/ethereum-sync-test/values.yaml \
      #       -f ./charts/ethereum-sync-test/values/tests/starts-syncing.yaml \
      #       -f ./charts/ethereum-sync-test/values/networks/${{ matrix.network }}.yaml \
      #       -f ./charts/ethereum-sync-test/values/clients/execution/${{ matrix.execution }}.yaml \
      #       -f ./charts/ethereum-sync-test/values/clients/consensus/${{ matrix.consensus }}.yaml

      - name: Install chart
        run: >
          helm install ethereum-sync-test ./charts/ethereum-sync-test \
            -f ./charts/ethereum-sync-test/values.yaml \
            -f ./charts/ethereum-sync-test/values/tests/starts-syncing.yaml \
            -f ./charts/ethereum-sync-test/values/networks/${{ matrix.network }}.yaml \
            -f ./charts/ethereum-sync-test/values/clients/execution/${{ matrix.execution }}.yaml \
            -f ./charts/ethereum-sync-test/values/clients/consensus/${{ matrix.consensus }}.yaml

      - name: Run test
        run: >
          helm test ethereum-sync-test --timeout=10m

      - name: Coordinator Pod Logs
        if: always()
        run: >
          kubectl logs pod/$(kubectl get pods -o name | grep ethereum-sync-test | cut -d/ -f2) -c coordinator --tail 250
      - name: Execution Pod Logs
        if: always()
        run: >
          kubectl logs pod/$(kubectl get pods -o name | grep ethereum-sync-test | cut -d/ -f2) -c ${{ matrix.execution }} --tail 250
      - name: Consensus Pod Logs
        if: always()
        run: >
          kubectl logs pod/$(kubectl get pods -o name | grep ethereum-sync-test | cut -d/ -f2) -c ${{ matrix.consensus }}-beacon --tail 250
